MotiCv/MotiCv/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MotiCv.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MotiCv/MotiCv/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MotiCv.Models.DbContexts;
using MotiCv.Models.Entities;
using MotiCv.Models.ViewModels;

namespace MotiCv.Controllers
{
    public class BlogController : Controller
    {
        readonly MotiCvDbContext db;
        public BlogController(MotiCvDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(int pageIndex=1,int PageSize=3)
        {
            var model = db.Blogs.Where(x => x.DeletedByUserId == null);
            var pagedview = new PagedViewModel<Blog>(model,pageIndex,PageSize);

            return View(pagedview);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            ForBlogViewModel model = new ForBlogViewModel();
            model.Blogs = await db.Blogs.FirstOrDefaultAsync(x => x.DeletedByUserId == null && x.Id == id);
            model.Comments = await db.Comments.Where(c => c.DeletedByUserId == null && c.BlogId == id).ToListAsync();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Details(ForBlogViewModel model)
        {
            if (ModelState.IsValid)
            {
                Comment comment = new Comment();
                comment.BlogId = model.BlogId;
                comment.Name = model.Name;
                comment.Email = model.Email;
                comment.Website = model.Website;
                comment.Subject = model.Subject;
                comment.Massage = model.Massage;

                db.Comments.Add(comment);
                await db.SaveChangesAsync();
                return Json(new
                {
                    error = false,
                    massage = "Mesajiniz qeyde alindi"
                });
            }
            return Json(new
            {
                error=true,
                massage="Tekrar cehd edin"
            });
        }
    }
}

MotiCv/MotiCv/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MotiCv.Controllers
{
    public class PortfolioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MotiCv/MotiCv/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<nav>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-tabis" aria-expanded="false"> <span class="tittle">MENU</span> <span class="fa fa-navicon icon-nav"></span> </button>
    <div class="collapse navbar-collapse" id="nav-tabis">
        <ul class="isop-filter nav nav-pills">
            <li role="presentation" class="active"><a asp-controller="About" asp-action="Index"><i class="icon-user"></i> ABOUT ME</a></li>
            <li role="presentation"><a href="#"><i class="icon-book-open"></i>RESUME</a></li>
            <li role="presentation"><a asp-controller="Portfolio" asp-action="Index"><i class="icon-rocket"></i>PORTFOLIO</a></li>
            <li role="presentation"><a asp-controller="Blog" asp-action="Index"><i class="icon-note"></i>BLOG</a></li>
            <li role="presentation"><a asp-controller="Home" asp-action="Contact"> <i class="icon-pencil"></i>CONTACT ME</a></li>
        </ul>
    </div>
</nav>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="M_Adnan" />
    <title>Resume / CV HTML5 Template</title>
    <link href="~/Assets/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Assets/css/responsive.css" rel="stylesheet" />
    <link href="~/Assets/css/style.css" rel="stylesheet" />
    <link href="~/Assets/css/main.css" rel="stylesheet" />
    <link href="~/Assets/css/main.css" rel="stylesheet" />
    <link href="~/Assets/css/style.css" rel="stylesheet" />
    <link href="~/Assets/css/responsive.css" rel="stylesheet" />
    <link href="~/Assets/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Assets/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/main.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">

    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <script src="~/assets/js/vendors/modernizr.js"></script>
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body>

    <div id="wrap">

        <nav id="cd-lateral-nav">
            <h5 class="tittle">MotiCv</h5>
            <ul class="cd-navigation">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="About" asp-action="Index">About Me</a></li>
                <li><a asp-controller="Portfolio" asp-action="Index">Portfolio</a></li>
                <li><a asp-controller="Blog" asp-action="Index">Blog</a></li>
                <li><a asp-controller="Home" asp-action="Logout">Signout</a></li>
            </ul>
            <h5 class="tittle">Latest Post</h5>
            <ul class="latest-post">

                <li>
                    <div class="media">
                        <div class="media-left"> <a href="#."><img src="~/uploads/images/small-img.jpg" alt=""></a></div>
                        <div class="media-body">
                            <a href="#.">
                                Hello Itaewon
                                Project
                            </a>
                            <p class="font-crimson font-italic">Webdesign</p>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="media">
                        <div class="media-left"> <a href="#."><img src="~/uploads/images/small-img-1.jpg" alt=""></a></div>
                        <div class="media-body">
                            <a href="#.">Casual in grey</a>
                            <p class="font-crimson font-italic">Webdesign</p>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="media">
                        <div class="media-left"> <a href="#."><img src="~/uploads/images/small-img-2.jpg" alt=""></a></div>
                        <div class="media-body">
                            <a href="#.">Transittions</a>
                            <p class="font-crimson font-italic">Webdesign</p>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>

        <main class="cd-main-content">
            <div id="content" class="bg">
                <div class="resume">
                    <div class="container">

                        <div class="top-head">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h4>Resume </h4>
                                </div>
                                <div class="col-sm-6"> <a id="cd-menu-trigger" href="#0"><span class="cd-menu-icon"></span></a> </div>
                            </div>
                        </div>

                        <div class="row">

                            <div class="col-md-4">
                                <div class="side-bar">

                                    <h5 class="tittle">Professional Details</h5>
                                    <img src="~/uploads/images/avatar.jpg" class="img-responsive" alt="">

                                    @*layouta data vermek ucun wiewcomponent lazimdi bude componenti tanitmaq ucundu renderbody kimi*@
                                    @await Component.InvokeAsync("Layoutc")


                                    <h5 class="tittle">Attachments</h5>
                                    <div class="attach bor-btm padding-25">
                                        <ul>
                                            <li>
                                                <p><img src="~/uploads/images/pdf-icon.jpg" alt=""> Curriculum-Vitae.pdf <a href="#."><i class="fa fa-cloud-download"></i></a> <a href="#."><i class="fa fa-eye"></i></a></p>
                                            </li>
                                            <li>
                                                <p><img src="~/uploads/images/word-icon.jpg" alt=""> COE.docx <a href="#."><i class="fa fa-cloud-download"></i></a> <a href="#."><i class="fa fa-eye"></i></a></p>
                                            </li>
                                        </ul>
                                    </div>

                                    <h5 class="tittle">Social Profiles</h5>
                                    <div class="social-icon bor-btm padding-25">
                                        <ul>
                                            <li> <a href="https://www.facebook.com/"> <i class="fa fa-facebook"></i></a> </li>
                                            <li> <a href="https://www.google.com/"> <i class="fa fa-google"></i></a> </li>
                                            <li> <a href="https://twitter.com/"> <i class="fa fa-twitter"></i></a> </li>
                                            <li> <a href="https://www.linkedin.com/"> <i class="fa fa-linkedin"></i></a> </li>
                                            <li> <a href="https://www.skype.com/tr/"> <i class="fa fa-skype"></i></a> </li>
                                        </ul>
                                    </div>

                                    <h5 class="tittle">Contact Me</h5>
                                    <div class="contact padding-25">
                                        <div id="contact_message" class="success-msg"> <i class="fa fa-paper-plane-o"></i>Thank You. Your Message has been Submitted</div>
                                        @*layouta data vermek ucun wiewcomponent lazimdi bude componenti tanitmaq ucundu renderbody kimi*@
                                        @await Component.InvokeAsync("LayoutContact")

                                    </div>
                                </div>
                            </div>

                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer class="footer">
            <div class="rights">
                <p>© Copyright 2016 MotiCV. All right reserved.</p>
            </div>
        </footer>

    </div>

    <script src="https://kit.fontawesome.com/1154e1d6ee.js" crossorigin="anonymous"></script>

    <script src="~/assets/js/vendors/jquery/jquery.min.js"></script>
    <script src="~/assets/js/vendors/bootstrap.min.js"></script>
    <script src="~/assets/js/vendors/owl.carousel.min.js"></script>
    <script src="~/assets/js/vendors/jquery.isotope.min.js"></script>
    <script src="~/assets/js/main.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="~/assets/js/vendors/map.js"></script>
    <script>
        $(document).ready(function () {
            $('#contact_form').submit(function (e) {
                e.preventDefault();
                const valid = $(e.currentTarget).valid();

                if (valid != true) {
                    return;
                }
                const formdata = new FormData(e.currentTarget);

                $.ajax({
                    url: '/Home/Contact',
                    type: 'post',
                    data: formdata,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.error == false) {
                            location.reload();
                            alert(response.massage);
                        }
                        else {
                            alert(respose.massage);
                        }
                    },
                    error: function (response) {

                    }
                });

            });
        });
    </script>
    <script src="~/libs/jquery-validate/jquery.validate.js"></script>
    <script src="~/libs/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @RenderSection("addjs", required: false)
</body>

</html>